import { DifferentialDiagnosis } from '@/lib/types';

/**
 * Fresh clinical results generated by running Dorothy Robinson's transcript 
 * through the clinical engine API. These results are in English and include
 * comprehensive differential diagnoses and treatment recommendations.
 */

export interface DemoClinicalData {
  primaryDiagnosis: {
    name: string;
    code: string;
    confidence: number;
    description: string;
  };
  differentialDiagnoses: Array<{
    name: string;
    likelihood: string;
    keyFactors: string;
    priority: number;
  }>;
  treatments: Array<{
    drug: string;
    status: string;
    rationale: string;
  }>;
}

// New clinical results from our successful API call
export const demoClinicalResults: DemoClinicalData = {
  // Primary diagnosis from clinical engine
  primaryDiagnosis: {
    name: "Fecal impaction",
    code: "K56.41",
    confidence: 90,
    description: "Fecal impaction with severe constipation requiring aggressive bowel regimen and medical intervention"
  },
  
  // Differential diagnoses from clinical engine
  differentialDiagnoses: [
    {
      name: "Opioid-Induced Constipation",
      likelihood: "High (90%)",
      keyFactors: "Recent hydrocodone use post-dental surgery, 6-day constipation history",
      priority: 1
    },
    {
      name: "Fecal Impaction", 
      likelihood: "Medium (60%)",
      keyFactors: "Abdominal distension, hard stool on rectal exam, radiographic findings",
      priority: 2
    },
    {
      name: "Dehydration Related Functional Constipation",
      likelihood: "Medium (70%)",
      keyFactors: "Poor fluid intake (1 glass water/day), low-fiber diet (fast food)",
      priority: 3
    },
    {
      name: "Partial Large Bowel Obstruction",
      likelihood: "Low (30%)", 
      keyFactors: "Colonic fecal retention on imaging, no complete obstruction signs",
      priority: 4
    },
    {
      name: "Secondary Constipation Due to AML History",
      likelihood: "Low (10%)",
      keyFactors: "History of acute myelomonocytic leukemia, potential medication effects",
      priority: 5
    }
  ],
  
  // Treatment recommendations from clinical engine
  treatments: [
    {
      drug: "Polyethylene glycol 3350 17g every 6 hours until bowel movement, then 17g nightly for 14 days",
      status: "Prescribed",
      rationale: "Osmotic laxative for severe fecal impaction with maintenance therapy to prevent recurrence"
    },
    {
      drug: "Docusate sodium 200mg twice daily",
      status: "Prescribed", 
      rationale: "Stool softener to facilitate easier bowel movements and reduce straining"
    },
    {
      drug: "Glycerin suppository every 12 hours as needed",
      status: "As needed",
      rationale: "Rectal stimulant if no bowel movement occurs within 12 hours"
    },
    {
      drug: "High-fiber diet with 25-30g fiber daily",
      status: "Patient education",
      rationale: "Dietary modification to prevent future constipation episodes and promote regular bowel function"
    },
    {
      drug: "Increased fluid intake to 8-10 glasses of water daily", 
      status: "Patient education",
      rationale: "Adequate hydration essential for preventing constipation and supporting treatment effectiveness"
    }
  ]
};

/**
 * Convert demo clinical results to DifferentialDiagnosis format for UI components
 */
export function getDemoDifferentialDiagnoses(): DifferentialDiagnosis[] {
  return demoClinicalResults.differentialDiagnoses.map(dx => ({
    name: dx.name,
    likelihood: dx.likelihood,
    keyFactors: dx.keyFactors,
    priority: dx.priority
  }));
} 